c1:
	clang-11 --sysroot=/home/jiangyikun/wasm/wasi-sdk-12.0/share/wasi-sysroot c1.c -o c1.wasm
c2:
	clang-11 --sysroot=/home/jiangyikun/wasm/wasi-sdk-12.0/share/wasi-sysroot c2.c -o c2.wasm
clean:
	rm *.wasm 